platform :ios, '8.0'

target 'SCHProgress' do
    pod 'Masonry'
    pod 'SDWebImage'
    pod 'MJExtension'
    pod 'MBProgressHUD'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Bugly', '~> 2.5.0'
    pod 'BlocksKit' #block链
    pod 'BaiduMapKit' #百度地图

end
